'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';

// Template interface
interface Template {
  id: string;
  name: string;
  modality: string;
  bodyPart: string;
  description: string;
  isGlobal: boolean;
  content?: string;
  createdAt: string;
  updatedAt: string;
}

// Mock templates for development (same as templates page)
const mockTemplates: Template[] = [
  {
    id: 'tpl-001',
    name: 'Chest X-Ray Standard',
    modality: 'X-Ray',
    bodyPart: 'Chest',
    description: 'Standard chest X-ray report template with PA and lateral views',
    isGlobal: true,
    content: 'FINDINGS:\n\nThe heart size is normal. The lungs are clear without focal consolidation, pleural effusion, or pneumothorax.\n\nIMPRESSION:\n\nNo acute cardiopulmonary findings.',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'tpl-002',
    name: 'CT Abdomen',
    modality: 'CT',
    bodyPart: 'Abdomen',
    description: 'CT scan of abdomen and pelvis with and without contrast',
    isGlobal: true,
    content: 'TECHNIQUE:\n\nCT of the abdomen and pelvis was performed with oral and IV contrast.\n\nFINDINGS:\n\nLiver, spleen, pancreas, and adrenal glands are unremarkable.\n\nIMPRESSION:\n\nNo acute findings.',
    createdAt: '2024-01-12T14:30:00Z',
    updatedAt: '2024-01-12T14:30:00Z',
  },
  {
    id: 'tpl-003',
    name: 'MRI Brain',
    modality: 'MRI',
    bodyPart: 'Head',
    description: 'Standard brain MRI with diffusion-weighted imaging',
    isGlobal: false,
    content: 'TECHNIQUE:\n\nMRI of the brain was performed without contrast.\n\nFINDINGS:\n\nNo acute intracranial abnormality.\n\nIMPRESSION:\n\nUnremarkable MRI of the brain.',
    createdAt: '2024-01-14T09:15:00Z',
    updatedAt: '2024-01-14T09:15:00Z',
  },
];

// Helper to get templates from localStorage
function getStoredTemplates(): Template[] {
  if (typeof window === 'undefined') return [];
  const stored = localStorage.getItem('ai-rad-templates');
  if (!stored) return [];
  try {
    return JSON.parse(stored);
  } catch {
    return [];
  }
}

// Helper to get and update usage stats
function getUsageStats(): { reportsGenerated: number; transcriptionMinutes: number } {
  if (typeof window === 'undefined') return { reportsGenerated: 0, transcriptionMinutes: 0 };
  const stored = localStorage.getItem('ai-rad-usage');
  if (!stored) return { reportsGenerated: 0, transcriptionMinutes: 0 };
  try {
    return JSON.parse(stored);
  } catch {
    return { reportsGenerated: 0, transcriptionMinutes: 0 };
  }
}

function incrementReportCount() {
  const stats = getUsageStats();
  stats.reportsGenerated += 1;
  localStorage.setItem('ai-rad-usage', JSON.stringify(stats));
}

export default function GeneratePage() {
  const [templates, setTemplates] = useState<Template[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>('');
  const [findings, setFindings] = useState('');
  const [generatedReport, setGeneratedReport] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  // Load templates on mount
  useEffect(() => {
    const storedTemplates = getStoredTemplates();
    // Combine mock templates with stored ones (stored take precedence by ID)
    const storedIds = new Set(storedTemplates.map(t => t.id));
    const combinedTemplates = [
      ...storedTemplates,
      ...mockTemplates.filter(t => !storedIds.has(t.id)),
    ];
    setTemplates(combinedTemplates);
    setIsLoading(false);
  }, []);

  const selectedTemplate = templates.find(t => t.id === selectedTemplateId);

  const handleGenerate = async () => {
    if (!selectedTemplateId || !findings.trim()) return;

    setIsGenerating(true);

    // Simulate AI generation (in production, this would call OpenAI)
    await new Promise(resolve => setTimeout(resolve, 1500));

    const template = templates.find(t => t.id === selectedTemplateId);
    const report = `RADIOLOGY REPORT

Template: ${template?.name || 'Unknown'}
Modality: ${template?.modality || 'Unknown'}
Body Part: ${template?.bodyPart || 'Unknown'}

CLINICAL INDICATION:
${findings}

${template?.content || 'No template content available.'}

---
Generated by AI Radiologist`;

    setGeneratedReport(report);
    setIsGenerating(false);

    // Increment the report count in usage stats
    incrementReportCount();
  };

  if (isLoading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <div className="mb-4 text-4xl">Loading...</div>
          <p className="text-text-secondary">Loading templates...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl p-6">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-text-primary">Generate Report</h1>
        <p className="mt-1 text-text-secondary">
          Select a template and provide findings to generate an AI-powered radiology report
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Input Section */}
        <div className="space-y-6">
          {/* Template Selection */}
          <Card>
            <CardHeader>
              <CardTitle>1. Select Template</CardTitle>
              <CardDescription>Choose a report template to use</CardDescription>
            </CardHeader>
            <CardContent>
              <select
                value={selectedTemplateId}
                onChange={(e) => setSelectedTemplateId(e.target.value)}
                className="w-full rounded-md border border-border bg-surface px-3 py-2 text-text-primary focus:border-brand focus:outline-none focus:ring-1 focus:ring-brand"
                data-testid="template-dropdown"
              >
                <option value="">Select a template...</option>
                <optgroup label="Personal Templates">
                  {templates.filter(t => !t.isGlobal).map(template => (
                    <option key={template.id} value={template.id} data-testid={`template-option-${template.id}`}>
                      {template.name} ({template.modality} - {template.bodyPart})
                    </option>
                  ))}
                </optgroup>
                <optgroup label="Global Templates">
                  {templates.filter(t => t.isGlobal).map(template => (
                    <option key={template.id} value={template.id} data-testid={`template-option-${template.id}`}>
                      {template.name} ({template.modality} - {template.bodyPart})
                    </option>
                  ))}
                </optgroup>
              </select>
              {selectedTemplate && (
                <p className="mt-2 text-sm text-text-secondary">
                  {selectedTemplate.description}
                </p>
              )}
            </CardContent>
          </Card>

          {/* Findings Input */}
          <Card>
            <CardHeader>
              <CardTitle>2. Enter Findings</CardTitle>
              <CardDescription>Provide clinical findings or transcribed notes</CardDescription>
            </CardHeader>
            <CardContent>
              <Textarea
                value={findings}
                onChange={(e) => setFindings(e.target.value)}
                placeholder="Enter clinical findings, observations, or paste transcribed notes..."
                rows={6}
                data-testid="findings-input"
              />
            </CardContent>
          </Card>

          {/* Generate Button */}
          <Button
            onClick={handleGenerate}
            disabled={!selectedTemplateId || !findings.trim() || isGenerating}
            className="w-full"
            data-testid="generate-button"
          >
            {isGenerating ? 'Generating...' : 'Generate Report'}
          </Button>
        </div>

        {/* Output Section */}
        <div>
          <Card className="h-full">
            <CardHeader>
              <CardTitle>Generated Report</CardTitle>
              <CardDescription>Your AI-generated radiology report will appear here</CardDescription>
            </CardHeader>
            <CardContent>
              {generatedReport ? (
                <div className="space-y-4">
                  <pre className="whitespace-pre-wrap rounded-md bg-surface-secondary p-4 text-sm text-text-primary font-mono" data-testid="generated-report">
                    {generatedReport}
                  </pre>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => navigator.clipboard.writeText(generatedReport)}>
                      Copy to Clipboard
                    </Button>
                    <Button variant="outline" size="sm">
                      Export PDF
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="flex h-64 flex-col items-center justify-center text-center">
                  <div className="mb-4 text-5xl">📄</div>
                  <p className="text-text-secondary">
                    Select a template and enter findings to generate a report
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
